# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16347d5039a8eec6e279e18524acfbb0a664f0b5ceae9af1f451c40a60fac72d2552c443ca8a4fbd7bef11a8860ddf3425b7b639274de1850ee6d458641b1745

test:
  secret_key_base: 09b547f42f786c0a835d96af5f0686bb14b07ad40cf203762a3afe2752f1c24db324c5be07abe33f4871d50f490a78035574150e59dcd6b7d10b3fe10c794166

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
